POST http://localhost:3003/api/blogs

Content-Type: application/json
{
    "title": "BlaaBlaa",
    "author": "Bertil Bertillson",
    "url": "http://localhost:3003/api/bloglist",
    "likes": "0"
}

